const FRAMEWORK = {
  TJS: "Transformers.js",
  TVM: "TVM",
  MEDIAPIPE: "MediaPipe",
  JS: "Vanilla JavaScript",
  ONNX: "ONNX Runtime Web",
  UNITY: "Unity",
  THREEJS: "Three.js",
  PLAYCANVAS: "PlayCanvas",
  BABYLONJS: "Babylon.js",
};

const CATEGORY = {
  WEBAI: "WebAI", // AI/ML focused demos
  WEBGPU: "WebGPU", // Graphics/compute focused demos
};

const demos = [
  {
    id: "webgpu-ministral3",
    category: CATEGORY.WEBAI,
    date: "2025-12-02",
    desc: "Mistral 3 multimodal model",
    framework: FRAMEWORK.TJS,
    url: "https://huggingface.co/spaces/mistralai/Ministral_3B_WebGPU",
  },
  {
    id: "webgpu-supertonic",
    category: CATEGORY.WEBAI,
    date: "2025-11-25",
    desc: "blazingly fast text-to-speech",
    framework: FRAMEWORK.TJS,
    url: "https://huggingface.co/spaces/webml-community/Supertonic-TTS-WebGPU",
  },
  {
    id: "webgpu-sam3",
    category: CATEGORY.WEBAI,
    date: "2025-11-20",
    desc: "segment anything with concepts",
    framework: FRAMEWORK.TJS,
    url: "https://huggingface.co/spaces/webml-community/SAM3-Tracker-WebGPU",
  },
  {
    id: "webgpu-granite-docling",
    category: CATEGORY.WEBAI,
    date: "2025-10-08",
    desc: "state-of-the-art document parsing",
    framework: FRAMEWORK.TJS,
    url: "https://huggingface.co/spaces/ibm-granite/granite-docling-258M-WebGPU",
  },
  {
    id: "webgpu-aquarium",
    category: CATEGORY.WEBGPU,
    date: "2025-10-01",
    desc: "WebGPU Aquarium",
    framework: FRAMEWORK.JS,
    url: "https://webgfx.github.io/aquarium-web/webgpu/aquarium/",
  },
  {
    id: "webgpu-gaussian-splatting-playcanvas",
    category: CATEGORY.WEBGPU,
    date: "2025-09-22",
    desc: "WebGPU Gaussian Splatting with PlayCanvas",
    framework: FRAMEWORK.PLAYCANVAS,
    url: "https://playcanv.as/e/p/Zp9Oh1ia/",
  },
  {
    id: "webgpu-gaussian-splatting-threejs",
    category: CATEGORY.WEBGPU,
    date: "2025-09-22",
    desc: "WebGPU Gaussian Splatting with Three.js",
    framework: FRAMEWORK.THREEJS,
    url: "https://projects.markkellogg.org/threejs/demo_gaussian_splats_3d.php",
  },
  {
    id: "webgpu-dinov3",
    category: CATEGORY.WEBAI,
    date: "2025-09-07",
    desc: "DINOv3 Video Tracking",
    framework: FRAMEWORK.TJS,
    url: "https://huggingface.co/spaces/webml-community/DINOv3-video-tracking",
  },
  {
    id: "webgpu-embeddinggemma",
    category: CATEGORY.WEBAI,
    date: "2025-09-07",
    desc: "Google EmbeddingGemma",
    framework: FRAMEWORK.TJS,
    url: "https://huggingface.co/spaces/webml-community/embeddinggemma-webgpu",
  },
  {
    id: "webgpu-fastvlm",
    category: CATEGORY.WEBAI,
    date: "2025-09-07",
    desc: "Apple FastVLM",
    framework: FRAMEWORK.TJS,
    url: "https://huggingface.co/spaces/webml-community/fastvlm-webgpu",
  },
  {
    // Tiny Llama model (23M parameters) on 3 million high-quality @lichess games
    id: "webgpu-chess",
    category: CATEGORY.WEBAI,
    date: "2025-07-23",
    desc: "WebGPU Chess",
    framework: FRAMEWORK.TJS,
    url: "https://lazy-guy.github.io/chess-llama/",
  },
  {
    // Silero VAD for voice activity detection, Whisper for speech recognition, SmolLM2-1.7B for text generation, Kokoro for text to speech
    id: "webgpu-conversation",
    category: CATEGORY.WEBAI,
    date: "2025-06-24",
    desc: "Conversational WebGPU",
    framework: FRAMEWORK.TJS,
    url: "https://huggingface.co/spaces/webml-community/conversational-webgpu",
  },
  {
    id: "webgpu-prismatic",
    category: CATEGORY.WEBGPU,
    date: "2025-06-22",
    desc: "Unity Project Prismatic",
    framework: FRAMEWORK.UNITY,
    url: "https://www.crazygames.com/game/project-prismatic",
  },
  {
    id: "webgpu-boatattack",
    category: CATEGORY.WEBGPU,
    date: "2025-06-22",
    desc: "Unity BoatAttack",
    framework: FRAMEWORK.UNITY,
    url: "https://boatattack-webgpu-updates-branch-a7.netlify.app/",
  },
  {
    id: "webgpu-janus-pro-1b",
    category: CATEGORY.WEBAI,
    date: "2025-02-03",
    desc: "DeepSeek-Janus-Pro-1B",
    framework: FRAMEWORK.TJS,
    url: "https://huggingface.co/spaces/webml-community/janus-pro-webgpu",
  },
  {
    id: "webgpu-deepseek-r1-qwen-1.5b",
    category: CATEGORY.WEBAI,
    date: "2025-01-26",
    desc: "DeepSeek-R1-Distill-Qwen-1.5B",
    framework: FRAMEWORK.TJS,
    url: "https://huggingface.co/spaces/webml-community/deepseek-r1-webgpu",
  },
  {
    id: "webgpu-smollm2",
    category: CATEGORY.WEBAI,
    date: "2024-12-25",
    desc: "SmolLM2, a blazingly fast and powerful SLM",
    framework: FRAMEWORK.TJS,
    url: "https://huggingface.co/spaces/HuggingFaceTB/SmolLM2-1.7B-Instruct-WebGPU",
  },
  {
    id: "webgpu-outetts",
    category: CATEGORY.WEBAI,
    date: "2024-12-25",
    desc: "OuteTTS, multilingual text-to-speech model",
    framework: FRAMEWORK.TJS,
    url: "https://huggingface.co/spaces/webml-community/text-to-speech-webgpu",
  },
  {
    id: "webgpu-moonshine",
    category: CATEGORY.WEBAI,
    date: "2024-12-25",
    desc: "Moonshine, a real-time speech recognition model",
    framework: FRAMEWORK.TJS,
    url: "https://huggingface.co/spaces/webml-community/moonshine-web",
  },
  {
    id: "webgpu-llama32",
    category: CATEGORY.WEBAI,
    date: "2024-10-02",
    desc: "Meta Llama 3.2 1B",
    framework: FRAMEWORK.TJS,
    url: "https://huggingface.co/spaces/webml-community/llama-3.2-webgpu",
  },
  {
    id: "webgpu-whisper-large",
    category: CATEGORY.WEBAI,
    date: "2024-10-02",
    desc: "OpenAI Whisper Large V3 Turbo",
    framework: FRAMEWORK.TJS,
    url: "https://huggingface.co/spaces/webml-community/whisper-large-v3-turbo-webgpu",
  },
  {
    id: "webgpu-phi35-mini",
    category: CATEGORY.WEBAI,
    date: "2024-08-25",
    desc: "Phi 3.5 mini, Language model by Microsoft",
    framework: FRAMEWORK.TJS,
    url: "https://huggingface.co/spaces/webml-community/phi-3.5-webgpu",
  },
  {
    id: "webgpu-qwen2",
    category: CATEGORY.WEBAI,
    date: "2024-06-10",
    desc: "Qwen2 0.5B Instruct, multilingual language model",
    framework: FRAMEWORK.TJS,
    url: "https://huggingface.co/spaces/Xenova/webgpu-chat-qwen2",
  },
  {
    id: "webgpu-smollm",
    category: CATEGORY.WEBAI,
    date: "2024-07-18",
    desc: "SmolLM, a blazingly fast and powerful SLM",
    framework: FRAMEWORK.TJS,
    url: "https://huggingface.co/spaces/HuggingFaceTB/SmolLM-360M-Instruct-WebGPU",
  },
  {
    id: "webgpu-webllm",
    category: CATEGORY.WEBAI,
    date: "2024-06-09",
    desc: "WebLLM, high-performance in-browser LLM inference engine",
    framework: FRAMEWORK.TVM,
    url: "https://chat.webllm.ai/",
  },
  {
    id: "webgpu-whisper-base",
    category: CATEGORY.WEBAI,
    date: "2024-06-10",
    desc: "Real-time speech recognition with OpenAI Whisper Base",
    framework: FRAMEWORK.TJS,
    url: "https://huggingface.co/spaces/Xenova/realtime-whisper-webgpu",
  },
  {
    id: "webgpu-gemini",
    category: CATEGORY.WEBAI,
    date: "2024-07-18",
    desc: "Google Gemini Nano integration with Chrome",
    framework: FRAMEWORK.TJS,
    url: "https://huggingface.co/spaces/Xenova/experimental-built-in-ai-chat",
  },
  {
    id: "webgpu-moondream",
    category: CATEGORY.WEBAI,
    date: "2024-06-10",
    desc: "Moondream, vision-language model",
    framework: FRAMEWORK.TJS,
    url: "https://huggingface.co/spaces/Xenova/experimental-moondream-webgpu",
  },
  {
    id: "webgpu-florence2",
    category: CATEGORY.WEBAI,
    date: "2024-06-27",
    desc: "Microsoft Florence2 - Advanced computer vision model",
    framework: FRAMEWORK.TJS,
    url: "https://huggingface.co/spaces/Xenova/florence2-webgpu",
  },
  {
    id: "webgpu-benchmark",
    category: CATEGORY.WEBAI,
    date: "2024-06-08",
    desc: "Benchmark to compare performance of WebGPU vs WASM",
    framework: FRAMEWORK.TJS,
    url: "https://huggingface.co/spaces/Xenova/webgpu-embedding-benchmark",
  },
  {
    id: "webgpu-clip",
    category: CATEGORY.WEBAI,
    date: "2024-06-08",
    desc: "OpenAI CLIP for computer vision tasks",
    framework: FRAMEWORK.TJS,
    url: "https://huggingface.co/spaces/Xenova/webgpu-clip",
  },
  {
    id: "webgpu-gemma",
    category: CATEGORY.WEBAI,
    date: "2024-06-08",
    desc: "Gemma - Advanced AI model showcase",
    framework: FRAMEWORK.MEDIAPIPE,
    url: "./demos/webgpu-gemma/gemma.html",
  },
  {
    id: "webgpu-mobilenetv4",
    category: CATEGORY.WEBAI,
    date: "2024-06-24",
    desc: "MobileNetV4, real-time image classification",
    framework: FRAMEWORK.TJS,
    url: "https://huggingface.co/spaces/Xenova/webgpu-mobilenet",
  },
  {
    id: "webgpu-modnet",
    category: CATEGORY.WEBAI,
    date: "2024-06-08",
    desc: "MODNet, real-time video background removal",
    framework: FRAMEWORK.TJS,
    url: "https://huggingface.co/spaces/Xenova/webgpu-video-background-removal",
  },
  {
    id: "webgpu-sam",
    category: CATEGORY.WEBAI,
    date: "2024-06-08",
    desc: `SAM, AI model from Meta that can "cut out" any object`,
    framework: FRAMEWORK.TJS,
    url: "https://huggingface.co/spaces/Xenova/segment-anything-webgpu",
  },
  {
    id: "webgpu-sd-turbo",
    category: CATEGORY.WEBAI,
    date: "2024-06-08",
    desc: "SD-Turbo, transform words into stunning AI visuals",
    framework: FRAMEWORK.ONNX,
    url: "./demos/webgpu-stable-diffusion/stable-diffusion.html",
  },
];
