const FRAMEWORK = {
  TJS: "Transformers.js",
  TVM: "TVM",
  MEDIAPIPE: "MediaPipe",
  JS: "Vanilla JavaScript",
}

const API = {
  WASM: "WASM",
  WEBGPU: "WebGPU"
};
const demos = [
  {
    id: "webgpu-llama32",
    api: API.WEBGPU,
    date: "2024-10-02",
    framework: FRAMEWORK.TJS,
    desc: "Meta Llama 3.2 1B",
    url: "https://huggingface.co/spaces/webml-community/llama-3.2-webgpu",
  },
  {
    id: "webgpu-whisper-large",
    api: API.WEBGPU,
    date: "2024-10-02",
    framework: FRAMEWORK.TJS,
    desc: "OpenAI Whisper Large V3 Turbo",
    url: "https://huggingface.co/spaces/webml-community/whisper-large-v3-turbo-webgpu",
  },
  {
    id: "webgpu-florence2",
    api: API.WEBGPU,
    date: "2024-06-27",
    framework: FRAMEWORK.TJS,
    desc: "Microsoft Florence2",
    url: "https://huggingface.co/spaces/Xenova/florence2-webgpu",
  },
  {
    id: "webgpu-benchmark",
    api: API.WEBGPU,
    date: "2024-06-08",
    framework: FRAMEWORK.TJS,
    desc: "Benchmark to compare perf of WebGPU vs Wasm",
    url: "https://huggingface.co/spaces/Xenova/webgpu-embedding-benchmark",
  },
  {
    id: "webgpu-clip",
    api: API.WEBGPU,
    date: "2024-06-08",
    framework: FRAMEWORK.TJS,
    desc: "OpenAI Clip for computer vision tasks",
    url: "https://huggingface.co/spaces/Xenova/webgpu-clip",
  },
  {
    id: "webgpu-gemini",
    desc: "Google Gemini Nano integration with Chrome Canary/Dev",
    url: "https://huggingface.co/spaces/Xenova/experimental-built-in-ai-chat",
    api: API.WEBGPU,
    framework: FRAMEWORK.TJS,
    date: "2024-07-18",
  },
  {
    id: "webgpu-gemma",
    desc: "Gemma",
    url: "./demos/webgpu-gemma/gemma.html",
    api: API.WEBGPU,
    framework: FRAMEWORK.MEDIAPIPE,
    date: "2024-06-08",
  },
  {
    id: "webgpu-mobilenetv4",
    desc: "MobileNetV4, real-time image classification",
    url: "https://huggingface.co/spaces/Xenova/webgpu-mobilenet",
    api: API.WEBGPU,
    framework: FRAMEWORK.TJS,
    date: "2024-06-24",
  },
  {
    id: "webgpu-modnet",
    desc: "MODNet, realtime Video Background Removal",
    url: "https://huggingface.co/spaces/Xenova/webgpu-video-background-removal",
    api: API.WEBGPU,
    framework: FRAMEWORK.TJS,
    date: "2024-06-08",
  },
  {
    id: "webgpu-moondream",
    desc: "Moondream, vision-Language Model",
    url: "https://huggingface.co/spaces/Xenova/experimental-moondream-webgpu",
    api: API.WEBGPU,
    framework: FRAMEWORK.TJS,
    date: "2024-06-10",
  },
  {
    id: "webgpu-phi35-mini",
    desc: "Phi 3.5 mini, Language model released in Aug 2024 by Microsoft",
    url: "https://huggingface.co/spaces/webml-community/phi-3.5-webgpu",
    api: API.WEBGPU,
    framework: FRAMEWORK.TJS,
    date: "2024-08-25",
  },
  {
    id: "webgpu-qwen2",
    desc: "Qwen2 0.5B Instruct, language understanding/generation, multilingual capability, coding, mathematics, etc.",
    url: "https://huggingface.co/spaces/Xenova/webgpu-chat-qwen2",
    api: API.WEBGPU,
    framework: FRAMEWORK.TJS,
    date: "2024-06-10",
  },
  {
    id: "webgpu-sam",
    desc: `SAM, AI model from Meta that can "cut out" any object`,
    url: "https://huggingface.co/spaces/Xenova/segment-anything-webgpu",
    api: API.WEBGPU,
    framework: FRAMEWORK.TJS,
    date: "2024-06-08",
  },
  {
    id: "webgpu-sd-turbo",
    desc: "SD-Turbo, transform your words into stunning AI visuals with SD-Turbo",
    url: "./demos/webgpu-stable-diffusion/stable-diffusion.html",
    api: API.WEBGPU,
    framework: "ONNX Runtime Web",
    date: "2024-06-08",
  },
  {
    id: "webgpu-smollm",
    desc: "SmolLM, a blazingly fast and powerful SLM",
    url: "https://huggingface.co/spaces/HuggingFaceTB/SmolLM-360M-Instruct-WebGPU",
    api: API.WEBGPU,
    framework: FRAMEWORK.TJS,
    date: "2024-07-18",
  },
  {
    id: "webgpu-webllm",
    desc: "WebLLM, high-performance in-browser LLM inference engine",
    url: "https://chat.webllm.ai/",
    api: API.WEBGPU,
    framework: FRAMEWORK.TVM,
    date: "2024-06-09",
  },
  {
    id: "webgpu-whisper-base",
    desc: "Real-time speech recognition with OpenAI Whisper Base across 100 different languages",
    url: "https://huggingface.co/spaces/Xenova/realtime-whisper-webgpu",
    api: API.WEBGPU,
    framework: FRAMEWORK.TJS,
    date: "2024-06-10",
  },
];