const FRAMEWORK = {
  TJS: "Transformers.js",
  TVM: "TVM",
  MEDIAPIPE: "MediaPipe",
  JS: "Vanilla JavaScript",
}

const API = {
  WASM: "WASM",
  WEBGPU: "WebGPU"
};
const demos = [
  {
    id: "webgpu-janus-pro-1b",
    api: API.WEBGPU,
    date: "2025-02-03",
    desc: "DeepSeek-Janus-Pro-1B",
    framework: FRAMEWORK.TJS,
    url: "https://huggingface.co/spaces/webml-community/janus-pro-webgpu",
  },
  {
    id: "webgpu-deepseek-r1-qwen-1.5b",
    api: API.WEBGPU,
    date: "2025-01-26",
    desc: "DeepSeek-R1-Distill-Qwen-1.5B",
    framework: FRAMEWORK.TJS,
    url: "https://huggingface.co/spaces/webml-community/deepseek-r1-webgpu",
  },
  {
    id: "webgpu-smollm2",
    api: API.WEBGPU,
    date: "2024-12-25",
    desc: "SmolLM2, a blazingly fast and powerful SLM",
    framework: FRAMEWORK.TJS,
    url: "https://huggingface.co/spaces/HuggingFaceTB/SmolLM2-1.7B-Instruct-WebGPU",
  },
  {
    id: "webgpu-outetts",
    api: API.WEBGPU,
    date: "2024-12-25",
    desc: "OuteTTS, multilingual (English, Chinese, Korean & Japanese) text-to-speech model",
    framework: FRAMEWORK.TJS,
    url: "https://huggingface.co/spaces/webml-community/text-to-speech-webgpu",
  },
  {
    id: "webgpu-moonshine",
    api: API.WEBGPU,
    date: "2024-12-25",
    desc: "Moonshine, a real-time speech recognition model",
    framework: FRAMEWORK.TJS,
    url: "https://huggingface.co/spaces/webml-community/moonshine-web",
  },
  {
    id: "webgpu-llama32",
    api: API.WEBGPU,
    date: "2024-10-02",
    desc: "Meta Llama 3.2 1B",
    framework: FRAMEWORK.TJS,
    url: "https://huggingface.co/spaces/webml-community/llama-3.2-webgpu",
  },
  {
    id: "webgpu-whisper-large",
    api: API.WEBGPU,
    date: "2024-10-02",
    desc: "OpenAI Whisper Large V3 Turbo",
    framework: FRAMEWORK.TJS,
    url: "https://huggingface.co/spaces/webml-community/whisper-large-v3-turbo-webgpu",
  },
  {
    id: "webgpu-florence2",
    api: API.WEBGPU,
    date: "2024-06-27",
    desc: "Microsoft Florence2",
    framework: FRAMEWORK.TJS,
    url: "https://huggingface.co/spaces/Xenova/florence2-webgpu",
  },
  {
    id: "webgpu-benchmark",
    api: API.WEBGPU,
    date: "2024-06-08",
    desc: "Benchmark to compare perf of WebGPU vs Wasm",
    framework: FRAMEWORK.TJS,
    url: "https://huggingface.co/spaces/Xenova/webgpu-embedding-benchmark",
  },
  {
    id: "webgpu-clip",
    api: API.WEBGPU,
    date: "2024-06-08",
    desc: "OpenAI Clip for computer vision tasks",
    framework: FRAMEWORK.TJS,
    url: "https://huggingface.co/spaces/Xenova/webgpu-clip",
  },
  {
    id: "webgpu-gemini",
    api: API.WEBGPU,
    date: "2024-07-18",
    desc: "Google Gemini Nano integration with Chrome Canary/Dev",
    framework: FRAMEWORK.TJS,
    url: "https://huggingface.co/spaces/Xenova/experimental-built-in-ai-chat",
  },
  {
    id: "webgpu-gemma",
    api: API.WEBGPU,
    date: "2024-06-08",
    desc: "Gemma",
    framework: FRAMEWORK.MEDIAPIPE,
    url: "./demos/webgpu-gemma/gemma.html",
  },
  {
    id: "webgpu-mobilenetv4",
    api: API.WEBGPU,
    date: "2024-06-24",
    desc: "MobileNetV4, real-time image classification",
    framework: FRAMEWORK.TJS,
    url: "https://huggingface.co/spaces/Xenova/webgpu-mobilenet",
  },
  {
    id: "webgpu-modnet",
    api: API.WEBGPU,
    date: "2024-06-08",
    desc: "MODNet, realtime Video Background Removal",
    framework: FRAMEWORK.TJS,
    url: "https://huggingface.co/spaces/Xenova/webgpu-video-background-removal",
  },
  {
    id: "webgpu-moondream",
    api: API.WEBGPU,
    date: "2024-06-10",
    desc: "Moondream, vision-Language Model",
    framework: FRAMEWORK.TJS,
    url: "https://huggingface.co/spaces/Xenova/experimental-moondream-webgpu",
  },
  {
    id: "webgpu-phi35-mini",
    api: API.WEBGPU,
    date: "2024-08-25",
    desc: "Phi 3.5 mini, Language model released in Aug 2024 by Microsoft",
    framework: FRAMEWORK.TJS,
    url: "https://huggingface.co/spaces/webml-community/phi-3.5-webgpu",
  },
  {
    id: "webgpu-qwen2",
    api: API.WEBGPU,
    date: "2024-06-10",
    desc: "Qwen2 0.5B Instruct, language understanding/generation, multilingual capability, coding, mathematics, etc.",
    framework: FRAMEWORK.TJS,
    url: "https://huggingface.co/spaces/Xenova/webgpu-chat-qwen2",
  },
  {
    id: "webgpu-sam",
    api: API.WEBGPU,
    date: "2024-06-08",
    desc: `SAM, AI model from Meta that can "cut out" any object`,
    framework: FRAMEWORK.TJS,
    url: "https://huggingface.co/spaces/Xenova/segment-anything-webgpu",
  },
  {
    id: "webgpu-sd-turbo",
    api: API.WEBGPU,
    date: "2024-06-08",
    desc: "SD-Turbo, transform your words into stunning AI visuals with SD-Turbo",
    framework: "ONNX Runtime Web",
    url: "./demos/webgpu-stable-diffusion/stable-diffusion.html",
  },
  {
    id: "webgpu-smollm",
    api: API.WEBGPU,
    date: "2024-07-18",
    desc: "SmolLM, a blazingly fast and powerful SLM",
    framework: FRAMEWORK.TJS,
    url: "https://huggingface.co/spaces/HuggingFaceTB/SmolLM-360M-Instruct-WebGPU",
  },
  {
    id: "webgpu-webllm",
    api: API.WEBGPU,
    date: "2024-06-09",
    desc: "WebLLM, high-performance in-browser LLM inference engine",
    framework: FRAMEWORK.TVM,
    url: "https://chat.webllm.ai/",
  },
  {
    id: "webgpu-whisper-base",
    api: API.WEBGPU,
    date: "2024-06-10",
    desc: "Real-time speech recognition with OpenAI Whisper Base across 100 different languages",
    framework: FRAMEWORK.TJS,
    url: "https://huggingface.co/spaces/Xenova/realtime-whisper-webgpu",
  },
];